### ISSUE TITLE
After updating to newer MonoMod version, MonoMod fails w/ SetPublic error

### ISSUE THREAD

**Issue by 5FiftySix6** [0x0ade/MonoMod#26]
```csharp
1>  Unhandled Exception: System.InvalidOperationException: MonoMod can't set metadata token providers of the type Mono.Cecil.EventDefinition public.
1>     at MonoMod.Utils.MonoModExt.SetPublic(IMetadataTokenProvider mtp, Boolean p) in D:\home\Documents\GitHub\MonoMod\MonoMod.Utils\MonoModExt.cs:line 704
1>     at MonoMod.MonoModder.PatchEvent(TypeDefinition targetType, EventDefinition srcEvent, HashSet`1 propMethods) in D:\home\Documents\GitHub\MonoMod\MonoMod\MonoModder.cs:line 1227
1>     at MonoMod.MonoModder.PatchType(TypeDefinition type) in D:\home\Documents\GitHub\MonoMod\MonoMod\MonoModder.cs:line 1086
1>     at MonoMod.MonoModder.PatchModule(ModuleDefinition mod) in D:\home\Documents\GitHub\MonoMod\MonoMod\MonoModder.cs:line 1041
```

The only thing I changed besides updating the MonoMod exe and dlls was the changing of ```            MMILRT.Modder.ShouldCleanupAttrib = IsUselessAttrib;``` to ```            MonoModRule.Modder.ShouldCleanupAttrib = IsUselessAttrib;```

**Comment by 0x0ade** [comment]
Can you please try again with the latest changes on the master branch (https://github.com/0x0ade/MonoMod/commit/9e5783c845322357c3f1daab9030b7daee6c93bb)? It seems like you're trying to make an event public, which wasn't supported and silently failed until recently.

**Comment by 5FiftySix6** [comment]
Works now! tysm
